version: '3.8'

services:
  zenith-agent:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - MONGODB_URL=mongodb://mongo:27017
      - DATABASE_NAME=zenith_agent
    volumes:
      - ./logs:/app/logs
      - .:/app
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=zenith_agent
    restart: unless-stopped

volumes:
  mongodb_data: